### ISSUE TITLE
Add support for discord overlay

### ISSUE THREAD

**Issue by LittleEndu** [Kedyn/fusliez-notes#89]
I mean the link generated by https://streamkit.discord.com/overlay

You could read the info from here and add it to the bottom where there's enough space

**Comment by francistse23** [comment]
if you are referring to having an overlay version of our app like discord does, we're looking into that as outlined in #28

**Comment by LittleEndu** [comment]
Nah, I want who is speaking to appear in the app. The built-in discord overlay is not working properly all the time so I would like this as a baclup

**Comment by francistse23** [comment]
I see. if you've watched fuslie's (and friends) streams, you might have seen the overlay they use. the user bubble shows up as the user speaks.

in terms of setting that up and whether that's only on OBS, i'm not sure

if that isn't what you're looking for, I may be interested in looking into how to build one

closing issue since it's not related to the notes app itself

**Comment by LittleEndu** [comment]
> closing issue since it's not related to the notes app itself

it is related to the notes app. I want the app to have some way to display the same information that https://streamkit.discord.com/overlay does. 

It might be possible to do with the same link that's generated by the overlay site (if CORS doesn't stop that) or there might be something in discord API that I'm not aware of that could be used instead. Then you could have the user of the notes app log in with discord to see who is speaking in their voice channel

**Comment by francistse23** [comment]
@Kedyn feel free to weigh in on this

in my opinion, this overextends and complicates what the author and other contributors have in mind in terms of the app's functionality.

while I see the value of implementing this as part of the app, this is the only feedback we have received regarding implementing a discord overlay for voice chat. 

as mentioned previously, I am not against the idea and might be interested in implementing the overlay and integrate it with the notes app rather than bundling them together
