### ISSUE TITLE
Option to use detailed map

### ISSUE THREAD

**Issue by ryuujin** [Kedyn/fusliez-notes#94]
Option to swap the maps out to detailed versions that have been made using screenshots of the map. For newer players still trying to learn the maps, being able to see what it looks like on the map could be helpful.

Sorry if this isn't the place to post this, I remember there was a feedback thing on the website but I can't find it anymore.

**Comment by francistse23** [comment]
hey ryuujin, thanks for the feedback. You can still find the feedback form at the bottom of the page. It'll open a new tab with the form

The team had the thought of swapping the maps with a more detailed version or give users the option to swap them as you suggested. The app has been drawing some criticism of it being a "cheat," even though the author and the other contributors have no intention of making it so. 

It is my understanding that we won't be making more features/enhancements to the map. 

thank you for using our app. we appreciate it! we also welcome any other feedback or comments you may have

@Kedyn if you agree with the above, please close the issue. otherwise, please comment

**Comment by Kedyn** [comment]
I do not have anything against changing the maps, but they must be the same format as the ones we have, meaning they have to be svgs so that they can be translated easily. I do not think changing the maps would change anything that is not already there.

But as you say, we are not going to be adding any new features/enhancements.

**Comment by francistse23** [comment]
i'm trying to see if I can create a detailed version of each map.

will send to you to see if it works once I'm done with the draft

**Comment by ryuujin** [comment]
@francistse23 
Thanks! I think I was on mobile at the time and couldn't find it. I see it on desktop. Thanks for giving it a shot guys, I think the notepad is a great tool for those that need help organizing and people shouldn't be so harsh!

**Comment by francistse23** [comment]
the only one i've come across is The Skeld. the other 2 maps have something similar but they have text over them, so I need to figure out how to remove them

**Comment by francistse23** [comment]
I am reaching out to some people on Reddit who have made the maps from the game. Trying to get their permission to use it. So far one has agreed and he has made two maps (Mira and Polus). just need to make sure we give him credit in the acknowledgement/credit/contributor section (u/mooseknuckle_king)

still trying to get a hold on creator of the Skeld map

**Comment by francistse23** [comment]
just got permission from the Skeld map creator (u/Stark_001001), same as the other author/creator, just need to make sure we include them in the readme as contributors

and to be clear, it is my understanding that these creators only want their work to be used as long as the app remains **free**

**Comment by francistse23** [comment]
@Kedyn 

how do we feel about this?

![Screenshot 2020-10-26 162649](https://user-images.githubusercontent.com/38173305/97239165-3a994580-17a8-11eb-96ea-d8e205795de5.png)


if this looks good, i'll go ahead and make one for Mira and Polus

**Comment by Kedyn** [comment]
Looks good to me. The text are svg elements right?

**Comment by francistse23** [comment]
everything is the same, except the image source. I did create a separate component because the text positioning is different for all elements
