### ISSUE TITLE
Layout isn't very usable on vertical screens

### ISSUE THREAD

**Issue by Jameskmonger** [Kedyn/fusliez-notes#99]
![image](https://user-images.githubusercontent.com/2037007/97749701-6d647600-1ae7-11eb-9ffd-d820357a133c.png)

Maybe an alternative would be to stack them vertically when portrait (a simple media query and some flexbox should solve this)

Happy to play around and raise a PR :)

**Comment by francistse23** [comment]
hey James, thanks for your feedback

can you be more specific with your environment and device? (screen size, OS, browser, etc.)

we do have a mobile layout set for tablet and mobile, but maybe that parameter needs to be adjusted

**Comment by mozi-h** [comment]
Let me add some more details, current behaviour is as follows:
- 1450+ px width: horizontal layout, everything is usable ✔️
- 925+ px width: horizontal layout, the map gets comically small; unusable ❗
- 847+ px width: horizontal layout, the map gets `overflow: hidden`'d while comically small ❗
- 550+ px width: mobile layout, everything is usable ✔️
- 320+ px width: mobile layout, everything but the map is usable (gets worse, of course; but we can't create more screen out of thin air, sadly) ✔️
Anything below is smaller than an iPhone SE and belongs into a museum.

> Perhaps set the breakpoint to around 1450px width.
> Maybe make this value adjustable for edgecases where the user would prefer the other layout with a screen size of just around the breakpoint.

Also, minor issue: When downsizing, marked players on the map can get "adjusted" out of view or into other regions (inconsistent; fixed with the reset button).

**Comment by Jameskmonger** [comment]
Apologies for the late reply here @francistse23 

This is on a Windows PC with a vertical screen. 1809x1080 according to `window.innerHeight` and `innerWidth`

**Comment by Kedyn** [comment]
Hello, for those who had issue with the vertical screen. Few versions ago, I tried to address this issue with the "hide left side button" that makes the map take most of the width.

Also, I know it might not be the most aesthetically pleasing, so if anyone can help make it a little better for those with vertical screens all contributions are welcome.
